"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.userRouter = void 0;
const express_1 = require("express");
const user_1 = require("../controller/user");
const middlewares_1 = require("../middlewares");
exports.userRouter = (0, express_1.Router)();
exports.userRouter.post('/likedbooks', middlewares_1.requireAuth, user_1.userBookLikes);
exports.userRouter.post('/viewedbooks', middlewares_1.requireAuth, user_1.userBookViews);
exports.userRouter.post('/namechange', middlewares_1.requireAuth, user_1.userNameChange);
